"use strict";
// ═══════════════════════════════════════════════════════════════
// J.A.R.V.I.S — WEBSITE BUILDER
// "hey jarvis build me a site for a coffee place" → Jarvis asks for
// a name → generates a real, self-contained single-page site (HTML
// + CSS + a little vanilla JS, no external deps) with Groq → saves
// it to disk → server.js hands the caller a same-origin preview URL
// to show in a window. "hey jarvis download <name>" later zips that
// same folder back up for the user.
// ═══════════════════════════════════════════════════════════════

const fs   = require("fs");
const path = require("path");
const archiver = require("archiver");

let Hermes = null;
try { Hermes = require("./hermes-engine"); } catch { Hermes = null; }

const SITES_DIR    = path.join(__dirname, "data", "sites");
const REGISTRY_FILE = path.join(SITES_DIR, "registry.json");
if (!fs.existsSync(SITES_DIR)) fs.mkdirSync(SITES_DIR, { recursive: true });

// ── REGISTRY ──────────────────────────────────────────────────
// Maps every site Jarvis has built this run (and across restarts)
// so a later "download <name>" can find it by name alone.
function loadRegistry() {
  try { return JSON.parse(fs.readFileSync(REGISTRY_FILE, "utf8")); }
  catch { return []; }
}
function saveRegistry(list) {
  try { fs.writeFileSync(REGISTRY_FILE, JSON.stringify(list, null, 2)); } catch { /* non-fatal */ }
}

function slugify(name) {
  const base = (name || "site")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "site";
  return `${base}-${Date.now().toString(36)}`;
}

// ── PROMPT ────────────────────────────────────────────────────
// Target bar: a self-taught design studio's flagship site — big,
// confident, editorial. Think dark cinematic coffee-brand landing
// pages, not a Bootstrap template. The model gets a LOT of creative
// license on layout; the hard rules only lock down what actually
// breaks the preview (no external assets, must be one file, must work).
const SYSTEM_PROMPT = `You are an award-winning web designer — the kind whose portfolio gets featured on Awwwards and CSS Design Awards. A client just hired you to build ONE complete, self-contained website. Output raw HTML only.

NEVER DO THIS (instant failure):
- Never mention who or what built the site — no "built by", "powered by", "generated by", no AI/assistant/Jarvis references anywhere in the copy, meta tags, comments, or footer. The client's brand is the only thing on the page.
- Never ship a generic centered-hero-then-3-cards-then-footer template. That layout is the default failure mode — actively avoid it.
- Never use lorem ipsum or vague placeholder copy like "coming soon" / "details about X" / "more info here". Every sentence is real, specific, on-brand copy you wrote for this exact business.
- Never reference external image URLs, fonts, icon libraries, or scripts (no unsplash, no Google Fonts link, no CDN). Everything is self-contained.

ART DIRECTION — pick a strong point of view and commit to it fully, don't hedge into something generic. Draw on things like:
- A confident, oversized type scale: display headlines at 80–160px+ that break the grid, mixed with a contrasting secondary typeface pairing (e.g. a heavy grotesque display next to a delicate italic serif) using only system font stacks (font-family stacks like Georgia/"Times New Roman"/serif or -apple-system/Segoe UI/sans-serif — no @font-face).
- Editorial structure: numbered sections (I, II, III...), running eyebrow labels in small tracked-out caps, pull quotes, asymmetric multi-column grids instead of everything centered.
- A considered, narrow color palette (2–4 colors) that actually fits the brand's mood — don't default to "dark background, one accent, white text" unless that's genuinely the right call for this business. Use CSS gradients, radial glows, noise/grain via SVG filters or repeating-gradient, blend modes, and geometric CSS shapes to build atmosphere in place of photography.
- Real interaction: scroll-triggered reveal animations (IntersectionObserver + CSS transitions/@keyframes), a custom cursor if it fits the vibe, hover states with personality, a sticky/transforming nav, parallax-ish depth via transform on scroll — all vanilla JS/CSS, no libraries.
- Specificity in content sections: a menu/services section with real item names, a short evocative description each, and prices — laid out like a considered spec sheet or index, not a bootstrap card grid. A story/about section with an actual point of view, not corporate filler. Hours/location. A contact section.
- Every business type gets its own distinct visual language: a coffee roaster should NOT look like a law firm should NOT look like a tattoo studio. Let the palette, type, and motion all serve the specific brand.

TECHNIQUES TO DRAW FROM — adapt these patterns (don't copy the exact colors/copy, they're just one example brand) to fit whatever business you're actually given:

Custom cursor + grain texture for atmosphere:
\`\`\`css
#cur{position:fixed;width:22px;height:22px;border:1px solid var(--accent);border-radius:50%;pointer-events:none;z-index:999;transform:translate(-50%,-50%);transition:width .2s,height .2s;}
#cur.big{width:52px;height:52px;}
.grain{position:fixed;inset:0;z-index:1;pointer-events:none;opacity:.05;mix-blend-mode:overlay;
  background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");}
\`\`\`
\`\`\`js
window.addEventListener("mousemove", e => { cur.style.left = e.clientX+"px"; cur.style.top = e.clientY+"px"; });
document.querySelectorAll("a,button,input,textarea").forEach(el => {
  el.addEventListener("mouseenter", () => cur.classList.add("big"));
  el.addEventListener("mouseleave", () => cur.classList.remove("big"));
});
\`\`\`

Scroll-reveal (apply the .reveal class to section content blocks, not whole sections):
\`\`\`css
.reveal{opacity:0;transform:translateY(28px);transition:opacity .9s ease,transform .9s ease;}
.reveal.in{opacity:1;transform:none;}
\`\`\`
\`\`\`js
const io = new IntersectionObserver(es => es.forEach(en => en.isIntersecting && en.target.classList.add("in")), {threshold:.15});
document.querySelectorAll(".reveal").forEach(el => io.observe(el));
\`\`\`

Numbered-section eyebrow pattern instead of plain <h2>s:
\`\`\`html
<div class="num">I — Origins</div>
<h2>A headline with real point of view, not a generic label.</h2>
\`\`\`

Spec-sheet row layout for menu/services/pricing instead of a card grid:
\`\`\`css
.row{display:grid;grid-template-columns:1fr auto;gap:.4rem 2rem;padding:1.6rem 0;border-top:1px solid var(--line);align-items:baseline;}
.row .desc{grid-column:1/-1;color:var(--dim);font-size:.95rem;}
.row .spec{grid-column:1/-1;display:flex;gap:2.2rem;flex-wrap:wrap;margin-top:.3rem;}
.row .spec span{font-size:.7rem;letter-spacing:.12em;text-transform:uppercase;color:var(--dim);}
\`\`\`

These are techniques, not a template — reinvent the palette, typography pairing, section order, and which of these devices actually get used based on what fits the specific business (a florist and a barbershop should NOT reach for the same set of these).

FUNCTIONAL RULES:
- Output ONLY the raw HTML document, starting with <!DOCTYPE html> and nothing else — no markdown fences, no commentary before or after.
- Everything in one file: CSS in a <style> tag in <head>, JS in a <script> tag before </body>.
- Include a <form id="contact-form"> with name/email/message fields. On submit, prevent default, POST JSON to relative path "/api/contact" via fetch, and show a tasteful inline success state whether or not the request succeeds (the fetch may fail in preview — catch it silently and still show success, since the visitor's submission experience must never look broken).
- Fully responsive from ~360px mobile up. Real contrast ratios — text must stay legible against every background it sits on.
- Semantic HTML, alt text on any decorative SVG, labeled form fields.`;

function extractHtml(raw) {
  let text = (raw || "").trim();
  text = text.replace(/^```(?:html)?\s*/i, "").replace(/```\s*$/i, "").trim();
  const start = text.search(/<!DOCTYPE html>|<html/i);
  if (start === -1) throw new Error("Model did not return an HTML document");
  return text.slice(start);
}

// Minimal fallback used only if Groq isn't configured or generation
// fails outright — keeps the feature from being a dead end. Still
// meant to look like a real, shipped site: no placeholder copy, no
// mention of how it was made.
function fallbackHtml(businessType, name) {
  const safeName = escapeHtml(name);
  const safeType = escapeHtml(businessType || "business");
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${safeName}</title>
<style>
  :root{--ink:#f3ece1;--bg:#120d0a;--ember:#e0783c;}
  *{box-sizing:border-box;}
  body{margin:0;font-family:-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--ink);}
  header{min-height:80vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:2rem;
    background:radial-gradient(circle at 50% 20%,rgba(224,120,60,.25),transparent 60%),var(--bg);}
  h1{font-family:Georgia,"Times New Roman",serif;font-weight:400;font-size:clamp(3rem,10vw,7rem);margin:0;letter-spacing:-.02em;}
  header p{margin-top:1rem;text-transform:uppercase;letter-spacing:.25em;font-size:.75rem;opacity:.7;}
  section{padding:6rem 2rem;max-width:760px;margin:0 auto;border-top:1px solid rgba(243,236,225,.1);}
  section h2{font-size:.75rem;text-transform:uppercase;letter-spacing:.25em;color:var(--ember);margin-bottom:1.5rem;}
  section p{font-size:1.25rem;line-height:1.6;font-weight:300;}
  form{display:grid;gap:1rem;margin-top:2rem;}
  input,textarea{background:transparent;border:none;border-bottom:1px solid rgba(243,236,225,.3);color:var(--ink);
    font:inherit;padding:.75rem 0;font-size:1rem;}
  input:focus,textarea:focus{outline:none;border-color:var(--ember);}
  button{justify-self:start;margin-top:.5rem;background:var(--ember);color:#1a0f08;border:none;padding:.9rem 2rem;
    font-size:.85rem;text-transform:uppercase;letter-spacing:.15em;cursor:pointer;}
  #confirm{display:none;color:var(--ember);margin-top:1rem;}
</style></head>
<body>
  <header><h1>${safeName}</h1><p>${safeType}</p></header>
  <section><h2>About</h2><p>${safeName} is being reworked with a sharper concept — check back shortly for the full story.</p></section>
  <section>
    <h2>Get in touch</h2>
    <form id="contact-form">
      <input name="name" placeholder="Name" required>
      <input name="email" type="email" placeholder="Email" required>
      <textarea name="message" placeholder="Message" rows="3"></textarea>
      <button type="submit">Send</button>
    </form>
    <p id="confirm">Thanks — we'll be in touch.</p>
  </section>
  <script>
    document.getElementById("contact-form").addEventListener("submit", function(e){
      e.preventDefault();
      var data = Object.fromEntries(new FormData(e.target));
      fetch("/api/contact", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify(data) }).catch(function(){});
      e.target.style.display = "none";
      document.getElementById("confirm").style.display = "block";
    });
  </script>
</body></html>`;
}
function escapeHtml(s) {
  return String(s || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

// ── BACKEND SCAFFOLD ─────────────────────────────────────────────
// A small, real Express backend written alongside the frontend so
// the site isn't just a static mockup — it has somewhere to actually
// send its contact-form submissions. This is generated deterministically
// (not by the model) so its routes always match what the frontend
// fetch() calls expect. The live preview only serves index.html as a
// static file (see server.js's /sites route); this backend is for
// when the user downloads the site and wants to actually run it.
function backendFiles(cleanName, cleanType, slug) {
  const pkg = {
    name: slug,
    version: "1.0.0",
    private: true,
    description: `Backend for ${cleanName}`,
    scripts: { start: "node server.js" },
    dependencies: { express: "^4.19.2" },
  };

  const serverJs = `// Backend for ${cleanName} (${cleanType})
// Serves the site and stores form submissions to disk.
//   npm install
//   npm start        -> http://localhost:3000
"use strict";
const express = require("express");
const fs = require("fs");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 3000;
const DATA_FILE = path.join(__dirname, "submissions.json");

app.use(express.json());
app.use(express.static(__dirname));

function readSubmissions() {
  try { return JSON.parse(fs.readFileSync(DATA_FILE, "utf8")); }
  catch { return []; }
}
function saveSubmission(entry) {
  const all = readSubmissions();
  all.push(entry);
  fs.writeFileSync(DATA_FILE, JSON.stringify(all, null, 2));
}

app.post("/api/contact", (req, res) => {
  const { name, email, message } = req.body || {};
  if (!email) return res.status(400).json({ ok: false, error: "email is required" });
  saveSubmission({ name: name || "", email, message: message || "", receivedAt: new Date().toISOString() });
  res.json({ ok: true });
});

app.get("/api/submissions", (_req, res) => res.json(readSubmissions()));

app.get("/api/health", (_req, res) => res.json({ ok: true, site: ${JSON.stringify(cleanName)} }));

app.listen(PORT, () => console.log(\`${cleanName} backend running at http://localhost:\${PORT}\`));
`;

  return { "package.json": JSON.stringify(pkg, null, 2), "server.js": serverJs };
}

// ── STREAMING BUILD ───────────────────────────────────────────
// The chat tool call registers the build (instant, no network wait)
// and hands the caller a buildId; the browser then opens the OS-style
// build window and connects to /api/sites/stream/:buildId, which
// drives streamBuild() below and forwards each token to the client as
// it's generated — the window shows the actual HTML materializing
// instead of a blank screen while Groq thinks.
const pendingBuilds = new Map(); // buildId -> { businessType, name }

function startBuild(businessType, name) {
  const cleanName = (name || "").trim();
  if (!cleanName) throw new Error("A business name is required");
  const buildId = `b_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  pendingBuilds.set(buildId, { businessType: (businessType || "business").trim(), name: cleanName });
  return buildId;
}

async function streamBuild(buildId, onDelta) {
  const job = pendingBuilds.get(buildId);
  if (!job) throw new Error("Unknown or already-completed build");
  pendingBuilds.delete(buildId);
  return buildSite(job.businessType, job.name, onDelta);
}

// ── BUILD ─────────────────────────────────────────────────────
async function buildSite(businessType, name, onDelta) {
  const cleanName = (name || "").trim();
  const cleanType = (businessType || "business").trim();
  if (!cleanName) throw new Error("A business name is required");

  let html;
  let streamedAny = false;
  try {
    if (!Hermes || !Hermes.isConfigured()) throw new Error("Build AI isn't configured — set GROQ_API_KEY in .env");
    const messages = [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: `Business type: ${cleanType}\nBusiness name: ${cleanName}\nBuild the full single-file website now.` },
    ];
    const raw = typeof onDelta === "function"
      ? await Hermes.groqFetchStream(messages, {
          model: Hermes.MODELS.code, temperature: 0.85, maxTokens: 16000,
          onDelta: (d) => { streamedAny = true; onDelta(d); },
        })
      : await Hermes.groqFetch(messages, Hermes.MODELS.code, 0.85, 16000);
    html = extractHtml(raw);
  } catch (e) {
    // Log the real reason so a run of fallbacks is diagnosable instead
    // of silently looking like "the AI just makes bad sites" — e.g. a
    // missing/invalid GROQ_API_KEY, an unrecognized model id, or a rate
    // limit will all land here.
    console.error(`[site-builder] generation failed for "${cleanName}":`, e.message);
    // Only substitute the fallback template if nothing had streamed yet —
    // once real tokens are already in the window, restarting mid-stream
    // would just garble what's on screen instead of recovering it.
    if (streamedAny) throw e;
    html = fallbackHtml(cleanType, cleanName);
    if (typeof onDelta === "function") onDelta(html, { fallback: true });
  }

  const slug = slugify(cleanName);
  const dir = path.join(SITES_DIR, slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "index.html"), html, "utf8");

  // Write a real (if minimal) backend alongside the frontend. The live
  // preview never touches this — /sites is served as static files — but
  // it's sitting in the folder for when the site is downloaded and the
  // user wants the contact form to actually go somewhere.
  const backend = backendFiles(cleanName, cleanType, slug);
  for (const [filename, contents] of Object.entries(backend)) {
    fs.writeFileSync(path.join(dir, filename), contents, "utf8");
  }

  const entry = {
    slug, name: cleanName, businessType: cleanType, createdAt: Date.now(),
    url: `/sites/${slug}/index.html`, hasBackend: true,
  };
  const registry = loadRegistry();
  registry.unshift(entry);
  saveRegistry(registry.slice(0, 200)); // keep it bounded

  return entry;
}

// ── LOOKUP ────────────────────────────────────────────────────
// Fuzzy-ish: exact name match wins, then case-insensitive substring
// either direction, most recent first.
function findSiteByName(name) {
  const q = (name || "").trim().toLowerCase();
  if (!q) return null;
  const registry = loadRegistry();
  let hit = registry.find((s) => s.name.toLowerCase() === q);
  if (!hit) hit = registry.find((s) => s.name.toLowerCase().includes(q) || q.includes(s.name.toLowerCase()));
  return hit || null;
}

function listSites() { return loadRegistry(); }

// ── ZIP ───────────────────────────────────────────────────────
function zipSite(slug, destStream) {
  return new Promise((resolve, reject) => {
    const dir = path.join(SITES_DIR, slug);
    if (!fs.existsSync(dir)) return reject(new Error("No such site on disk"));
    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.on("error", reject);
    archive.on("end", resolve);
    archive.pipe(destStream);
    archive.directory(dir, false);
    archive.finalize();
  });
}

module.exports = { buildSite, startBuild, streamBuild, findSiteByName, listSites, zipSite, SITES_DIR };
