"use strict";
// ═══════════════════════════════════════════════════════════════
// J.A.R.V.I.S — WEBSITE BUILDER
// "hey jarvis build me a site for a coffee place" → Jarvis asks for
// a name → generates a real, self-contained single-page site (HTML
// + CSS + a little vanilla JS, no external deps) with Groq → saves
// it to disk → server.js hands the caller a same-origin preview URL
// to show in a window. "hey jarvis download <name>" later zips that
// same folder back up for the user.
// ═══════════════════════════════════════════════════════════════

const fs   = require("fs");
const path = require("path");
const archiver = require("archiver");

let Hermes = null;
try { Hermes = require("./hermes-engine"); } catch { Hermes = null; }
let LocalLLM = null;
try { LocalLLM = require("./local-llm"); } catch { LocalLLM = null; }

const SITES_DIR    = path.join(__dirname, "data", "sites");
const REGISTRY_FILE = path.join(SITES_DIR, "registry.json");
if (!fs.existsSync(SITES_DIR)) fs.mkdirSync(SITES_DIR, { recursive: true });

// ── REGISTRY ──────────────────────────────────────────────────
// Maps every site Jarvis has built this run (and across restarts)
// so a later "download <name>" can find it by name alone.
function loadRegistry() {
  try { return JSON.parse(fs.readFileSync(REGISTRY_FILE, "utf8")); }
  catch { return []; }
}
function saveRegistry(list) {
  try { fs.writeFileSync(REGISTRY_FILE, JSON.stringify(list, null, 2)); } catch { /* non-fatal */ }
}

function slugify(name) {
  const base = (name || "site")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "site";
  return `${base}-${Date.now().toString(36)}`;
}

// ── PROMPT ────────────────────────────────────────────────────
// Target bar: a self-taught design studio's flagship site — big,
// confident, editorial. Think dark cinematic coffee-brand landing
// pages, not a Bootstrap template. The model gets a LOT of creative
// license on layout; the hard rules only lock down what actually
// breaks the preview (no external assets, must be one file, must work).
//
// Two versions of this prompt exist because Groq's free/on_demand
// tier caps qwen/qwen3.6-27b at a hard 8000 TPM — and that limit is
// charged against (system + user + max_tokens requested), not just
// what's actually generated. The full prompt below plus a realistic
// output length blows straight through that. So:
//   - PROMPT_CORE (~compact) is what actually gets sent to Groq.
//   - PROMPT_FULL (core + concrete technique snippets) is reserved
//     for local Ollama generation, which has no such cap — see
//     buildSite() below, which prefers local whenever it's reachable.
const PROMPT_CORE = `You are an award-winning web designer — the kind whose portfolio gets featured on Awwwards and CSS Design Awards. A client just hired you to build ONE complete, self-contained website. Output raw HTML only.

NEVER DO THIS (instant failure):
- Never mention who or what built the site — no "built by", "powered by", "generated by", no AI/assistant/Jarvis references anywhere in the copy, meta tags, comments, or footer.
- Never ship a generic centered-hero-then-3-cards-then-footer template — that's the default failure mode, actively avoid it.
- Never use lorem ipsum or vague placeholder copy like "coming soon". Every sentence is real, specific, on-brand copy for this exact business.
- Never reference external image URLs, fonts, icon libraries, or scripts. Everything self-contained.

ART DIRECTION — commit fully to one strong point of view, don't hedge into something generic:
- Oversized, confident type scale (display headlines 80-160px+), a contrasting type pairing (heavy grotesque + delicate italic serif), system font stacks only.
- Editorial structure: numbered sections (I, II, III), small tracked-out eyebrow labels, pull quotes, asymmetric grids instead of everything centered.
- A narrow, considered 2-4 color palette that fits THIS brand's mood. Build atmosphere with CSS gradients, radial glows, grain/noise, blend modes, geometric shapes — no photography needed.
- Real interaction: scroll-triggered reveal animations (IntersectionObserver), a custom cursor if it fits, personality in hover states, a spec-sheet/index style layout for menu-or-services items instead of generic cards.
- Every business gets its OWN visual language — a coffee roaster ≠ a law firm ≠ a tattoo studio.

FUNCTIONAL RULES:
- Output ONLY the raw HTML document starting with <!DOCTYPE html>, nothing else — no fences, no commentary.
- One file: CSS in <style> in <head>, JS in <script> before </body>.
- Include <form id="contact-form"> (name/email/message). On submit: preventDefault, POST JSON to "/api/contact" via fetch, catch failures silently, always show an inline success state.
- Fully responsive from ~360px up. Real contrast. Semantic HTML, labeled fields.`;

const PROMPT_TECHNIQUES = `

TECHNIQUES TO DRAW FROM — adapt these patterns (not the exact colors/copy) to whatever business you're given:

Custom cursor + grain texture:
\`\`\`css
#cur{position:fixed;width:22px;height:22px;border:1px solid var(--accent);border-radius:50%;pointer-events:none;z-index:999;transform:translate(-50%,-50%);transition:width .2s,height .2s;}
#cur.big{width:52px;height:52px;}
.grain{position:fixed;inset:0;z-index:1;pointer-events:none;opacity:.05;mix-blend-mode:overlay;
  background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='120' height='120'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");}
\`\`\`
\`\`\`js
window.addEventListener("mousemove", e => { cur.style.left = e.clientX+"px"; cur.style.top = e.clientY+"px"; });
document.querySelectorAll("a,button,input,textarea").forEach(el => {
  el.addEventListener("mouseenter", () => cur.classList.add("big"));
  el.addEventListener("mouseleave", () => cur.classList.remove("big"));
});
\`\`\`

Scroll-reveal (apply .reveal to section content blocks, not whole sections):
\`\`\`css
.reveal{opacity:0;transform:translateY(28px);transition:opacity .9s ease,transform .9s ease;}
.reveal.in{opacity:1;transform:none;}
\`\`\`
\`\`\`js
const io = new IntersectionObserver(es => es.forEach(en => en.isIntersecting && en.target.classList.add("in")), {threshold:.15});
document.querySelectorAll(".reveal").forEach(el => io.observe(el));
\`\`\`

Numbered-section eyebrow pattern instead of plain <h2>s:
\`\`\`html
<div class="num">I — Origins</div>
<h2>A headline with real point of view, not a generic label.</h2>
\`\`\`

Spec-sheet row layout for menu/services/pricing instead of a card grid:
\`\`\`css
.row{display:grid;grid-template-columns:1fr auto;gap:.4rem 2rem;padding:1.6rem 0;border-top:1px solid var(--line);align-items:baseline;}
.row .desc{grid-column:1/-1;color:var(--dim);font-size:.95rem;}
.row .spec{grid-column:1/-1;display:flex;gap:2.2rem;flex-wrap:wrap;margin-top:.3rem;}
.row .spec span{font-size:.7rem;letter-spacing:.12em;text-transform:uppercase;color:var(--dim);}
\`\`\`

These are techniques, not a template — reinvent the palette, typography, section order, and which of these actually get used based on what fits the specific business.`;

const SYSTEM_PROMPT_COMPACT = PROMPT_CORE; // sent to Groq — stays under its TPM cap
const SYSTEM_PROMPT_FULL    = PROMPT_CORE + PROMPT_TECHNIQUES; // sent to local Ollama — no cap to worry about

function extractHtml(raw) {
  let text = (raw || "").trim();
  text = text.replace(/^```(?:html)?\s*/i, "").replace(/```\s*$/i, "").trim();
  const start = text.search(/<!DOCTYPE html>|<html/i);
  if (start === -1) throw new Error("Model did not return an HTML document");
  return text.slice(start);
}

// Minimal fallback used only if Groq isn't configured or generation
// fails outright — keeps the feature from being a dead end. Still
// meant to look like a real, shipped site: no placeholder copy, no
// mention of how it was made.
function fallbackHtml(businessType, name) {
  const safeName = escapeHtml(name);
  const safeType = escapeHtml(businessType || "business");
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${safeName}</title>
<style>
  :root{--ink:#f3ece1;--bg:#120d0a;--ember:#e0783c;}
  *{box-sizing:border-box;}
  body{margin:0;font-family:-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--ink);}
  header{min-height:80vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:2rem;
    background:radial-gradient(circle at 50% 20%,rgba(224,120,60,.25),transparent 60%),var(--bg);}
  h1{font-family:Georgia,"Times New Roman",serif;font-weight:400;font-size:clamp(3rem,10vw,7rem);margin:0;letter-spacing:-.02em;}
  header p{margin-top:1rem;text-transform:uppercase;letter-spacing:.25em;font-size:.75rem;opacity:.7;}
  section{padding:6rem 2rem;max-width:760px;margin:0 auto;border-top:1px solid rgba(243,236,225,.1);}
  section h2{font-size:.75rem;text-transform:uppercase;letter-spacing:.25em;color:var(--ember);margin-bottom:1.5rem;}
  section p{font-size:1.25rem;line-height:1.6;font-weight:300;}
  form{display:grid;gap:1rem;margin-top:2rem;}
  input,textarea{background:transparent;border:none;border-bottom:1px solid rgba(243,236,225,.3);color:var(--ink);
    font:inherit;padding:.75rem 0;font-size:1rem;}
  input:focus,textarea:focus{outline:none;border-color:var(--ember);}
  button{justify-self:start;margin-top:.5rem;background:var(--ember);color:#1a0f08;border:none;padding:.9rem 2rem;
    font-size:.85rem;text-transform:uppercase;letter-spacing:.15em;cursor:pointer;}
  #confirm{display:none;color:var(--ember);margin-top:1rem;}
</style></head>
<body>
  <header><h1>${safeName}</h1><p>${safeType}</p></header>
  <section><h2>About</h2><p>${safeName} is being reworked with a sharper concept — check back shortly for the full story.</p></section>
  <section>
    <h2>Get in touch</h2>
    <form id="contact-form">
      <input name="name" placeholder="Name" required>
      <input name="email" type="email" placeholder="Email" required>
      <textarea name="message" placeholder="Message" rows="3"></textarea>
      <button type="submit">Send</button>
    </form>
    <p id="confirm">Thanks — we'll be in touch.</p>
  </section>
  <script>
    document.getElementById("contact-form").addEventListener("submit", function(e){
      e.preventDefault();
      var data = Object.fromEntries(new FormData(e.target));
      fetch("/api/contact", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify(data) }).catch(function(){});
      e.target.style.display = "none";
      document.getElementById("confirm").style.display = "block";
    });
  </script>
</body></html>`;
}
function escapeHtml(s) {
  return String(s || "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

// ── BACKEND SCAFFOLD ─────────────────────────────────────────────
// A small, real Express backend written alongside the frontend so
// the site isn't just a static mockup — it has somewhere to actually
// send its contact-form submissions. This is generated deterministically
// (not by the model) so its routes always match what the frontend
// fetch() calls expect. The live preview only serves index.html as a
// static file (see server.js's /sites route); this backend is for
// when the user downloads the site and wants to actually run it.
function backendFiles(cleanName, cleanType, slug) {
  const pkg = {
    name: slug,
    version: "1.0.0",
    private: true,
    description: `Backend for ${cleanName}`,
    scripts: { start: "node server.js" },
    dependencies: { express: "^4.19.2" },
  };

  const serverJs = `// Backend for ${cleanName} (${cleanType})
// Serves the site and stores form submissions to disk.
//   npm install
//   npm start        -> http://localhost:3000
"use strict";
const express = require("express");
const fs = require("fs");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 3000;
const DATA_FILE = path.join(__dirname, "submissions.json");

app.use(express.json());
app.use(express.static(__dirname));

function readSubmissions() {
  try { return JSON.parse(fs.readFileSync(DATA_FILE, "utf8")); }
  catch { return []; }
}
function saveSubmission(entry) {
  const all = readSubmissions();
  all.push(entry);
  fs.writeFileSync(DATA_FILE, JSON.stringify(all, null, 2));
}

app.post("/api/contact", (req, res) => {
  const { name, email, message } = req.body || {};
  if (!email) return res.status(400).json({ ok: false, error: "email is required" });
  saveSubmission({ name: name || "", email, message: message || "", receivedAt: new Date().toISOString() });
  res.json({ ok: true });
});

app.get("/api/submissions", (_req, res) => res.json(readSubmissions()));

app.get("/api/health", (_req, res) => res.json({ ok: true, site: ${JSON.stringify(cleanName)} }));

app.listen(PORT, () => console.log(\`${cleanName} backend running at http://localhost:\${PORT}\`));
`;

  return { "package.json": JSON.stringify(pkg, null, 2), "server.js": serverJs };
}

// ── STREAMING BUILD ───────────────────────────────────────────
// The chat tool call registers the build (instant, no network wait)
// and hands the caller a buildId; the browser then opens the OS-style
// build window and connects to /api/sites/stream/:buildId, which
// drives streamBuild() below and forwards each token to the client as
// it's generated — the window shows the actual HTML materializing
// instead of a blank screen while Groq thinks.
const pendingBuilds = new Map(); // buildId -> { businessType, name }

function startBuild(businessType, name) {
  const cleanName = (name || "").trim();
  if (!cleanName) throw new Error("A business name is required");
  const buildId = `b_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  pendingBuilds.set(buildId, { businessType: (businessType || "business").trim(), name: cleanName });
  return buildId;
}

async function streamBuild(buildId, onDelta) {
  const job = pendingBuilds.get(buildId);
  if (!job) throw new Error("Unknown or already-completed build");
  pendingBuilds.delete(buildId);
  return buildSite(job.businessType, job.name, onDelta);
}

// Env var override so the site builder can use a stronger local model
// (e.g. "qwen2.5-coder:14b") for generation quality without changing
// OLLAMA_MODEL used everywhere else in Jarvis for quick chat replies.
const SITE_OLLAMA_MODEL = process.env.SITE_BUILDER_OLLAMA_MODEL || (LocalLLM && LocalLLM.OLLAMA_MODEL) || "llama3.2:3b";

async function tryLocalOllama(cleanType, cleanName, onDelta) {
  if (!LocalLLM || !LocalLLM.isLocalMode()) return null;
  const serving = await LocalLLM.isOllamaServing().catch(() => false);
  if (!serving) return null;
  const pulled = await LocalLLM.isModelPulled(SITE_OLLAMA_MODEL).catch(() => false);
  if (!pulled) {
    console.warn(`[site-builder] Ollama is running but "${SITE_OLLAMA_MODEL}" isn't pulled — run: ollama pull ${SITE_OLLAMA_MODEL}. Falling back to Groq.`);
    return null;
  }
  const messages = [
    { role: "system", content: SYSTEM_PROMPT_FULL },
    { role: "user", content: `Business type: ${cleanType}\nBusiness name: ${cleanName}\nBuild the full single-file website now.` },
  ];
  // Ollama's bridge here doesn't stream — send the whole thing as one
  // delta so the build window still shows *something* land, just not
  // token-by-token. No TPM ceiling locally, so we can ask for a lot.
  const raw = await LocalLLM.ollamaText(messages, SITE_OLLAMA_MODEL, 0.85, 16000);
  const html = extractHtml(raw);
  if (typeof onDelta === "function") onDelta(html, { local: true });
  return html;
}

// Groq's free/on_demand tier for qwen/qwen3.6-27b caps at 8000 TPM —
// and that limit is charged against system+user+max_tokens REQUESTED,
// not just what's actually generated. So this path always uses the
// compact prompt and keeps max_tokens conservative enough to leave
// headroom, and if Groq still says the request is too large (a 413),
// retries once with an even smaller budget instead of just dying.
async function tryGroq(cleanType, cleanName, onDelta, onStreamStart) {
  if (!Hermes || !Hermes.isConfigured()) throw new Error("Build AI isn't configured — set GROQ_API_KEY in .env");
  const userMsg = { role: "user", content: `Business type: ${cleanType}\nBusiness name: ${cleanName}\nBuild the full single-file website now.` };

  const attempt = async (systemPrompt, maxTokens) => {
    const messages = [{ role: "system", content: systemPrompt }, userMsg];
    return typeof onDelta === "function"
      ? await Hermes.groqFetchStream(messages, {
          model: Hermes.MODELS.code, temperature: 0.85, maxTokens,
          onDelta: (d) => { onStreamStart(); onDelta(d); },
        })
      : await Hermes.groqFetch(messages, Hermes.MODELS.code, 0.85, maxTokens);
  };

  try {
    return extractHtml(await attempt(SYSTEM_PROMPT_COMPACT, 6000));
  } catch (e) {
    const tooLarge = /413|too large|reduce your message size/i.test(e.message || "");
    if (!tooLarge) throw e;
    console.warn(`[site-builder] Groq request still too large, retrying with a smaller budget: ${e.message}`);
    return extractHtml(await attempt(PROMPT_CORE, 3200));
  }
}

// ── BUILD ─────────────────────────────────────────────────────
async function buildSite(businessType, name, onDelta) {
  const cleanName = (name || "").trim();
  const cleanType = (businessType || "business").trim();
  if (!cleanName) throw new Error("A business name is required");

  let html;
  let streamedAny = false;
  try {
    html = await tryLocalOllama(cleanType, cleanName, onDelta);
    if (!html) html = await tryGroq(cleanType, cleanName, onDelta, () => { streamedAny = true; });
  } catch (e) {
    // Log the real reason so a run of fallbacks is diagnosable instead
    // of silently looking like "the AI just makes bad sites" — e.g. a
    // missing/invalid GROQ_API_KEY, an unrecognized model id, or a rate
    // limit will all land here.
    console.error(`[site-builder] generation failed for "${cleanName}":`, e.message);
    // Only substitute the fallback template if nothing had streamed yet —
    // once real tokens are already in the window, restarting mid-stream
    // would just garble what's on screen instead of recovering it.
    if (streamedAny) throw e;
    html = fallbackHtml(cleanType, cleanName);
    if (typeof onDelta === "function") onDelta(html, { fallback: true });
  }

  const slug = slugify(cleanName);
  const dir = path.join(SITES_DIR, slug);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "index.html"), html, "utf8");

  // Write a real (if minimal) backend alongside the frontend. The live
  // preview never touches this — /sites is served as static files — but
  // it's sitting in the folder for when the site is downloaded and the
  // user wants the contact form to actually go somewhere.
  const backend = backendFiles(cleanName, cleanType, slug);
  for (const [filename, contents] of Object.entries(backend)) {
    fs.writeFileSync(path.join(dir, filename), contents, "utf8");
  }

  const entry = {
    slug, name: cleanName, businessType: cleanType, createdAt: Date.now(),
    url: `/sites/${slug}/index.html`, hasBackend: true,
  };
  const registry = loadRegistry();
  registry.unshift(entry);
  saveRegistry(registry.slice(0, 200)); // keep it bounded

  return entry;
}

// ── LOOKUP ────────────────────────────────────────────────────
// Fuzzy-ish: exact name match wins, then case-insensitive substring
// either direction, most recent first.
function findSiteByName(name) {
  const q = (name || "").trim().toLowerCase();
  if (!q) return null;
  const registry = loadRegistry();
  let hit = registry.find((s) => s.name.toLowerCase() === q);
  if (!hit) hit = registry.find((s) => s.name.toLowerCase().includes(q) || q.includes(s.name.toLowerCase()));
  return hit || null;
}

function listSites() { return loadRegistry(); }

// ── ZIP ───────────────────────────────────────────────────────
function zipSite(slug, destStream) {
  return new Promise((resolve, reject) => {
    const dir = path.join(SITES_DIR, slug);
    if (!fs.existsSync(dir)) return reject(new Error("No such site on disk"));
    const archive = archiver("zip", { zlib: { level: 9 } });
    archive.on("error", reject);
    archive.on("end", resolve);
    archive.pipe(destStream);
    archive.directory(dir, false);
    archive.finalize();
  });
}

module.exports = { buildSite, startBuild, streamBuild, findSiteByName, listSites, zipSite, SITES_DIR };
